// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt2NnU_x8T1ldNJDUo_IqUXqvqRNOIvFY',
    appId: '1:426566689277:web:ad81f5534209d6f357f994',
    messagingSenderId: '426566689277',
    projectId: 'kantinkuproject',
    authDomain: 'kantinkuproject.firebaseapp.com',
    storageBucket: 'kantinkuproject.firebasestorage.app',
    measurementId: 'G-3EG5ERJK8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLSUwZxAr6Q5fJIL_i6MS4dEftNs6KNs0',
    appId: '1:426566689277:android:9f8e3dcf11b04c8157f994',
    messagingSenderId: '426566689277',
    projectId: 'kantinkuproject',
    storageBucket: 'kantinkuproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe9oxomvSmcRp_D0YVpQDKtx_HfKy10t4',
    appId: '1:426566689277:ios:7e0310632c0f3c6a57f994',
    messagingSenderId: '426566689277',
    projectId: 'kantinkuproject',
    storageBucket: 'kantinkuproject.firebasestorage.app',
    iosBundleId: 'com.example.kantinku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe9oxomvSmcRp_D0YVpQDKtx_HfKy10t4',
    appId: '1:426566689277:ios:7e0310632c0f3c6a57f994',
    messagingSenderId: '426566689277',
    projectId: 'kantinkuproject',
    storageBucket: 'kantinkuproject.firebasestorage.app',
    iosBundleId: 'com.example.kantinku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt2NnU_x8T1ldNJDUo_IqUXqvqRNOIvFY',
    appId: '1:426566689277:web:d8c0738c7466589557f994',
    messagingSenderId: '426566689277',
    projectId: 'kantinkuproject',
    authDomain: 'kantinkuproject.firebaseapp.com',
    storageBucket: 'kantinkuproject.firebasestorage.app',
    measurementId: 'G-TBK4QRL9LE',
  );
}
